name: base_M
model_params:
  arch: resnet50
  weights: null
  batch_size: 128
  optimizer:
    name: SGD
    params:
      lr: 0.01
      momentum: 0.9
      weight_decay: 0.0001
  scheduler:
    name: MultiStepLR
    params:
      gamma: 0.5
      milestones: [4, 8, 12, 13, 14, 15]
  partitionings:
    - coarse
    - middle
    - fine
trainer_params:
  gpus: 1
  max_epochs: 15
  precision: 16
